services:
  - type: web
    name: ai-invoice-extractor
    env: python

    buildCommand: "./build.sh"

    startCommand: "gunicorn file_extractor.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9